Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: "echo Hello"
  config.vm.define "app" do |app| 
   config.vm.box = "ubuntu/xenial64"
   config.vm.synced_folder ".", "/home/vagrant/app" 
   config.vm.network "private_network", ip: "192.168.56.2"
   config.vm.provision "shell", path: "./provision.sh"
  end
 
  config.vm.define "db" do |db|
    db.vm.box = "ubuntu/xenial64"
    db.vm.network "private_network", ip:"192.168.56.3"
    db.vm.synced_folder ".", "/home/vagrant/app"
    db.vm.provision "shell", path: "./provision.sh"
  end
end

