Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: "echo Hello"
  config.vm.define "db" do |db|
    db.vm.box = "ubuntu/xenial64"
    db.vm.network "private_network", ip:"192.168.56.4"
    db.vm.synced_folder ".", "/home/vagrant/app"
    db.vm.provision "shell", path: "./provision_db.sh"
  end
  config.vm.define "app" do |app| 
   app.vm.box = "ubuntu/xenial64"
   app.vm.synced_folder ".", "/home/vagrant/app" 
   app.vm.network "private_network", ip: "192.168.56.2"
   app.vm.provision "shell", path: "./provision.sh"
   #config.vm.provision "file", source: "/Users/venkateshvivekandhan/Desktop/devops_99/multi-machine-environment/starter-code/default", destination: "./etc/nginx/sites-avaiable/default"
   
  end
 
  #config.vm.define "dbv" do |dbv|
   # dbv.vm.box = "bento/ubuntu-18.04"
    #dbv.vm.network "private_network", ip:"192.168.56.3"
    #dbv.vm.synced_folder ".", "/home/vagrant/app"
    #dbv.vm.provision "shell", path: "./provision_db1.sh"
  #end
  
end

