Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"
  config.vm.network "forwarded_port", guest: 3000, host: 8080
# copy from local host to vm
  config.vm.synced_folder ".", "/home/vagrant/app" 
# config.vm.network "private_network", ip: "192.168.10.100"
# provisioning  
  config.vm.provision "shell", path: "./provision.sh"
end
